version: '3.8'

services:
  mongo:
    image: mongo:6.0
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongo_admin
      MONGO_INITDB_ROOT_PASSWORD: password

  app:
    build: .
    ports:
      - "5000:5000"
    environment:
      - MONGO_DETAILS=mongodb://mongo_admin:password@mongo:27017
    depends_on:
      - mongo
